### ISSUE TITLE
Update example

### ISSUE THREAD

**Issue by YuukanOO** [katzien/go-structure-examples#14]
Hi! Just found your talk and really appreciate it!

Thinking about how to handle an update use case using the **domain-hex** approach.

Based on the beer sample, let's say an update can update a beer `ShortDesc` only if the beer was added in the last month (so the field `Created` is needed). How do you approach it?

The `Created` field can not be added in the `updating.Beer` model and comes directly from the database so I'm pretty confused right now.

Thanks :)

**Comment by dgparker** [comment]
@YuukanOO I think you could solve this a couple ways but to be honest the problem is actually quite a bit more complicated than it might seem at first glance.

Really what we're trying to solve for is whether or not we should process an update to `ShortDesc` or HOW we should update `Beer`.

Building on your example this can only happen if the beer was added in the last month.

As you said we don't want to expose `Created` to the client. However, we need to expose something to the client otherwise how will they know they can update a `ShortDesc` which could lead to bad UX.

So one solution would be to add a field to `updating.Beer` and `listing.Beer` let's go with a `boolean` value `canUpdate` then when translating the struct from your db to `listing.Beer` we add our business logic i.e. `if Created < time` set `canUpdate` to true. This way on every request to `UpdateBeer` we can check the boolean value to determine whether or not we should update the `ShortDesc` or at least how we should make an update to `Beer`.

This solution however, requires you to trust your clients, i.e. one could manipulate the `canUpdate` field to `true`. This is not ideal considering in most cases you can't trust your clients. 

You could resolve this by adding a call to the repository for the specific beer being updated to confirm the `canUpdate` field is indeed actually true from inside your `updating.Beer` service.
```
func (s *service) UpdateBeer(b Beer) (Beer, error) {
	oldBeer := s.r.GetBeer(b.ID)
	if !oldBeer.CanUpdate {
		return Beer{}, ErrCantUpdate
	}
	return s.r.UpdateBeer(b)
}
```

Some other thoughts I had while thinking through this... From a performance perspective the cost of your database operation is really the main constraint. Say if `Beer` was some super complex object that resulted in a costly database operation you may benefit from abstracting this logic out even further into it's own function entirely like `UpdateShortDesc` and manage those separately from the larger object to reduce the cost of the operation.

**Comment by YuukanOO** [comment]
@dgparker Thanks for this reply, really appreciate it! Make sense to me, maybe we should add this example to the repo?
